name: hello world
on:
  push:
    branches: [main]  #[main,dev]
jobs:
  say-hello: #job id
    runs-on: ubuntu-latest # platform
    steps:
      - run: echo "TODAY = $(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY