name: hello world
on:
  push:
    path:
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches:  #[main,dev]
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
    type: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch: # run manual
jobs:
  say-hello: #job id
    runs-on: ubuntu-latest # platform
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY